#!/usr/bin/env python3
# dis START END : objdump lines between two hex addresses
import sys,re
s=int(sys.argv[1],16); e=int(sys.argv[2],16)
for line in open('/root/gh/game.dis'):
    m=re.match(r'^ *([0-9a-f]+):',line)
    if m:
        a=int(m.group(1),16)
        if s<=a<e: sys.stdout.write(line)
        elif a>=e: break
